### ISSUE TITLE
ERRO[0000] failed to resolve name: could not parse reference

### ISSUE THREAD

**Issue by drnic** [bstick12/pack-concourse-resource#5]
Any ideas why this resource might be failing after its successfully created the image?

<img width="608" alt="image" src="https://user-images.githubusercontent.com/108/64085437-11cd1a00-cd76-11e9-96a5-51c1adc5d609.png">

build url https://ci2.starkandwayne.com/teams/drnic/pipelines/sample-app-nodejs/jobs/build-image/builds/9

When I run the resulting image it works just fine:

```
docker run -ti -p 8080:8080 starkandwayne/sample-app-nodejs
```

My simple pipeline to reproduce the error:

```yaml
resources:
- name: git
  type: git
  source:
    uri: https://github.com/starkandwayne/sample-app-nodejs.git
- name: image
  type: pack-image-resource
  source:
    password: ((docker-hub-password))
    repository: starkandwayne/sample-app-nodejs:latest
    username: ((docker-hub-username))
resource_types:
- name: pack-image-resource
  type: docker-image
  source:
    repository: bstick12/pack-concourse-resource
  privileged: true
jobs:
- name: build-image
  plan:
  - get: git
    trigger: true
  - put: image
    params:
      build: git
      builder: cloudfoundry/cnb:cflinuxfs3
```
